<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    </head>
    <body style="width: 100%;">
        <table>
            <tr>
                <th colspan="8" align="center">SUNPRIDE FOODS INC.</th>
            </tr>
            <tr>
                <td colspan="8" align="center">SAP HEADER</td>
            </tr>
        </table>
        <table>
            <thead>
                <tr>
                    <th>Document Date</th>
                    <th>Posting Date</th>
                    <th>Document Type</th>
                    <th>Company Code</th>
                    <th>Reference</th>
                    <th>Header Text</th>
                    <th>REF</th>
                    <th>SEND</th>
                </tr>
            </thead>
            <tbody>
                @foreach($records as $index => $record)
                    <tr>
                        <td align="left" width="30">{{ date('mdy',strtotime($record->invoice_date)) }}</td>
                        <td align="left" width="30">{{ date('mdy',strtotime($record->invoice_posting_date)) }}</td>
                        <td align="left" width="30">{{ $record->document_type}}</td>
                        <td align="left" width="30">{{ $record->company_code }}</td>
                        <td align="left" width="30">{{ $record->invoice_number }}</td>
                        <td align="left" width="30">{{ $record->header_text}}</td>
                        <td align="left" width="30">{{ $index + 1 }}</td>
                        <td align="left" width="30"></td>
                    </tr>
                @endforeach
            </tbody>
        </table>
        <table>
            <tr>
                <th colspan="5" align="left">Generated By: {{ auth()->user()->firstname . ' ' .auth()->user()->lastname }}</th>
            </tr>
            <tr>
                <td colspan="5" align="left">Generated On: {{ date('F j,Y g:i:s A') }}</td>
            </tr>
        </table>
    </body>
</html>