<html>
<head>	
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<style>		
			
	</style>
</head>
<body>
	<table>
		<tbody>
			<tr>
				<th>Salesman Name:</th>
				<th>{{$replenishment->salesman}}</th>
				<th></th>											
			</tr>	
			<tr>
				<th>Junior Salesman:</th>
				<th>{{$replenishment->jr_salesman}}</th>
				<th></th>											
			</tr>
			<tr>
				<th>Van Code: </th>
				<th>{{$replenishment->van_code}}</th>
				<th></th>											
			</tr>
			<tr>
				<th>Count date:</th>
				<th>{{format_date($replenishment->replenish_date,'m/d/Y g:i A')}}</th>
				<th align="right">REPORT#{{latest_revision('vaninventory')}}</th>											
			</tr>
			<tr>
				<th>Count Sheet No:</th>
				<th>@if($replenishment->replenish){{$replenishment->replenish->reference_number}} @endif</th>
				<th align="right">REV#{{latest_revision('vaninventory')}}</th>											
			</tr>								
		</tbody>
	</table>
	<table>
		<thead>
			<tr>
				<th>Material Code</th>
				<th>Material Description</th>
				<th>Total Qty</th>							
			</tr>
		</thead>
					
		<tbody>
			@foreach($replenishment->items as $item)
				<tr>							
					<td>{{$item->item_code}}</td>
					<td>{{$item->description}}</td>
					<td class="quantity">{{$item->quantity}}</td>
				</tr>
			@endforeach									
		</tbody>				
	</table>	
	<table>
		<tbody>
			<tr>
				<th>Counted:</th>
				<th align="center">Confirmed:</th>
				<th align="center">Confirmed:</th>				
			</tr>	
			<tr>
				<th>&nbsp;</th>
				<th>&nbsp;</th>
				<th>&nbsp;</th>				
			</tr>
			<tr>
				<th>@if($replenishment->replenish) {{$replenishment->replenish->counted}} @endif</th>
				<th align="center">@if($replenishment->replenish){{$replenishment->replenish->confirmed}} @endif</th>
				<th align="center">@if($replenishment->replenish){{$replenishment->jr_salesman}} @endif</th>											
			</tr>									
		</tbody>
	</table>	
	
	<table>
		<tbody>
			<tr>
				<th colspan="2">LAST USED DOCUMENTS / RECEIPTS:</th>				
				<th align="center"></th>				
			</tr>	
			<tr>
				<th>LAST SR:</th>
				<th>@if($replenishment->replenish) {{$replenishment->replenish->last_sr}} @endif</th>
				<th></th>				
			</tr>
			<tr>
				<th>LAST RPRR:</th>
				<th>@if($replenishment->replenish) {{$replenishment->replenish->last_rprr}} @endif</th>
				<th></th>				
			</tr>
			<tr>
				<th>LAST CASH SLIP:</th>
				<th>@if($replenishment->replenish) {{$replenishment->replenish->last_cs}} @endif</th>
				<th></th>				
			</tr>
			<tr>
				<th>LAST DR:</th>
				<th>@if($replenishment->replenish) {{$replenishment->replenish->last_dr}} @endif</th>
				<th></th>				
			</tr>
			<tr>
				<th>LAST DDR:</th>
				<th>@if($replenishment->replenish) {{$replenishment->replenish->last_ddr}} @endif</th>
				<th></th>				
			</tr>									
		</tbody>
	</table>
	<table>
		<tbody>
			<tr>
				<th colspan="2">Generated By: {{auth()->user()->firstname}} {{auth()->user()->lastname}}</th>				
			</tr>
			<tr>
				<th colspan="2">Date Generated: {{date("m/d/Y g:i A")}}</th>
			</tr>
		</tbody>
	</table>	
</body>
</html>