<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <link rel="stylesheet" href="{{ URL::asset('js/components/packages/bootstrap/dist/css/bootstrap.min.css') }}"/>
        <link rel="stylesheet" href="{{ URL::asset('css/styles.css') }}"/>
        <style type="text/css">
            @page{
                size: landscape;
            }

            *{
                padding: 0;
                margin: 0;
                background-color: #FFF;
            }

            tbody:before,
            tbody:after{ 
                display: none;
            }
        </style>
    </head>
    <body style="width: 100%; background-color: #FFF;">
        <div style="margin: 0 auto;">
            <h3 style="width: 100%; text-align: center;">SUNPRIDE FOODS INC.</h3>
            <br>

            <h4 style="width: 100%; text-align: center;">{{ $period_label }}</h4>
            <br>

            <table class="table table-striped table-condensed table-bordered" style="border: 1px solid #000;">
                <tr style="border: 1px solid #000;">
                    <th colspan="2" style="border: 1px solid #000; font-size: 12px; font-family: 'Arial';">Reports Name</th>
                    <th colspan="{{ $limit_day + 1 }}" style="border: 1px solid #000; font-size: 12px; font-family: 'Arial';">Period</th>
                </tr>
                <tr style="border: 1px solid #000;">
                    <td style="width:100px; border: 1px solid #000; font-size: 12px; font-family: 'Arial';"></td>
                    <td style="width:100px; border: 1px solid #000; font-size: 12px; font-family: 'Arial';"></td>
                    @for ($day = 1; $day <= $limit_day; $day++)
                        <td class="text-center" style="width:10px; border: 1px solid #000; font-size: 12px; font-family: 'Arial';">{{ $day }}</td>
                    @endfor
                    <td style="width:10px; border: 1px solid #000; font-size: 12px; font-family: 'Arial';">STATUS</td>
                </tr>

                @foreach($report_data as $data)
                    <tr>
                        @if($data->row_span > 0)
                            <td style="width:100px; border: 1px solid #000; font-size: 12px; font-family: 'Arial';" rowspan="{{ $data->row_span }}">{{ $data->parent_name }}</td>
                        @endif
                        <td style="width:100px; border: 1px solid #000; font-size: 12px; font-family: 'Arial';">{{ $data->child_name }}</td>
                        @foreach($data->dates as $key => $value)
                            <td style="width:10px; border: 1px solid #000; font-size: 12px; font-family: 'Arial';">
                                @if($value === 'close')/@endif
                            </td>
                        @endforeach
                        <td style="width:10px; border: 1px solid #000; font-size: 12px; font-family: 'Arial';">{{ $data->period_status === 'open' || $data->period_status === 0 ? 'OPEN' : 'CLOSED' }}</td>
                    </tr>
                @endforeach
            </table>
            <h4 style="width: 100%;">Generated By: {{ $generated_by }}</h4>
            <br>
            <h4 style="width: 100%;">Date Generated: {{ date('F j,Y g:i:s A') }}</h4>
        </div>
    </body>
</html>