<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        @if($download_type == 'pdf')
            <link rel="stylesheet" href="{{ URL::asset('js/components/packages/bootstrap/dist/css/bootstrap.min.css') }}"/>
            <link rel="stylesheet" href="{{ URL::asset('css/styles.css') }}"/>
            <style type="text/css">
                @page{
                    size: landscape;
                }

                *{
                    padding: 0;
                    margin: 0;
                    background-color: #FFF;
                    font-family: 'Arial' !important;
                }

                tbody:before,
                tbody:after{ 
                    display: none;
                }

                .bordered{
                    width:100px;
                    border: 1px solid #000 !important;
                    font-size: 12px !important;
                }

                p{
                    margin-bottom: 10px !important;
                    font-size: 15px !important;
                }
            </style>
        @endif
    </head>
    <body style="width: 100%;">
        @if($download_type == 'pdf')
            <div style="margin: 0 auto; padding: 30px;">
                <h3 style="width: 100%; text-align: center;">SUNPRIDE FOODS INC.</h3>
                <br>

                <h4 style="width: 100%; text-align: center;">Auditor's List</h4>
                <br>

                <p>AUDITOR : {{ (!empty($filters) && array_key_exists('auditor',$filters) ? strtoupper($filters['auditor']) : 'ALL') }}</p>
                <p>SALESMAN : {{ (!empty($filters) && array_key_exists('salesman',$filters) ? strtoupper($filters['salesman']) : 'ALL') }}</p>
                <p>SALESMAN AREA : {{ (!empty($filters) && array_key_exists('area',$filters) ? strtoupper($filters['area']) : 'ALL') }}</p>
                <p>TYPE : {{ (!empty($filters) && array_key_exists('type',$filters) ? (strtoupper($filters['type'] == 'canned' ? 'Canned & Mixes' : 'Frozen & Kassel')) : 'ALL') }}</p>
                <p>PERIOD COVERED : {{ (!empty($filters) && array_key_exists('period_covered',$filters) ? strtoupper($filters['period_covered']) : 'ALL') }}</p>
                <br>
                <table class="table table-striped table-condensed table-bordered" style="border: 1px solid #000;">
                    <tr style="border: 1px solid #000;">
                        <th class="bordered">AUDITOR</th>
                        <th class="bordered">PERIOD COVERED</th>
                        <th class="bordered">TYPE</th>
                        <th class="bordered">SALESMAN</th>
                        <th class="bordered">SALESMAN AREA</th>
                    </tr>

                    @foreach($records as $record)
                        <tr>
                            <td class="bordered">{{ $record['user']['firstname'] . ' ' . $record['user']['lastname'] }}</td>
                            <td class="bordered">{{ date('F j,Y',strtotime($record['period_from'])) . ' - ' . date('F j,Y',strtotime($record['period_to'])) }}</td>
                            <td class="bordered">{{ strtoupper($record['type'] == 'canned' ? 'Canned & Mixes' : 'Frozen & Kassel') }}</td>
                            <td class="bordered">{{ $record['salesman']['salesman_name'] }}</td>
                            <td class="bordered">{{ $record['area']['area_name'] }}</td>
                        </tr>
                    @endforeach
                </table>
                <h4 style="width: 100%;">Generated By: {{ auth()->user()->firstname . ' ' .auth()->user()->lastname }}</h4>
                <br>
                <h4 style="width: 100%;">Generated On: {{ date('F j,Y g:i:s A') }}</h4>
            </div>
        @endif

        @if($download_type == 'xlsx')
            <table>
                <tr>
                    <th colspan="5" align="center">SUNPRIDE FOODS INC.</th>
                </tr>
                <tr>
                    <td colspan="5" align="center">Auditor's List</td>
                </tr>
                <tr>
                    <td colspan="5" align="left">AUDITOR : {{ !empty($filters) && array_key_exists('auditor',$filters) ? strtoupper($filters['auditor']) : 'ALL'}}</td>
                </tr>
                <tr>
                    <td colspan="5" align="left">SALESMAN : {{ !empty($filters) && array_key_exists('salesman',$filters) ? strtoupper($filters['salesman']) : 'ALL'}}</td>
                </tr>
                <tr>
                    <td colspan="5" align="left">SALESMAN AREA : {{ !empty($filters) && array_key_exists('area',$filters) ? strtoupper($filters['area']) : 'ALL'}}</td>
                </tr>
                <tr>
                    <td colspan="5" align="left">TYPE : {{ !empty($filters) && array_key_exists('type',$filters) ? (strtoupper($filters['type'] == 'canned' ? 'Canned & Mixes' : 'Frozen & Kassel')) : 'ALL'}}</td>
                </tr>
                <tr>
                    <td colspan="5" align="left">PERIOD COVERED : {{ !empty($filters) && array_key_exists('period_covered',$filters) ? strtoupper($filters['period_covered']) : 'ALL'}}</td>
                </tr>
            </table>
            <table>
                <thead>
                    <tr>
                        <th>AUDITOR</th>
                        <th>PERIOD COVERED</th>
                        <th>TYPE</th>
                        <th>SALESMAN</th>
                        <th>SALESMAN AREA</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($records as $record)
                    <tr>
                        <td align="left" width="30">{{ $record['user']['firstname'] . ' ' . $record['user']['lastname'] }}</td>
                        <td align="left" width="30">{{ date('F j,Y',strtotime($record['period_from'])) . ' - ' . date('F j,Y',strtotime($record['period_to'])) }}</td>
                        <td align="left" width="30">{{ strtoupper($record['type'] == 'canned' ? 'Canned & Mixes' : 'Frozen & Kassel') }}</td>
                        <td align="left" width="30">{{ $record['salesman']['salesman_name'] }}</td>
                        <td align="left" width="30">{{ $record['area']['area_name'] }}</td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
            <table>
                <tr>
                    <th colspan="5" align="left">Generated By: {{ auth()->user()->firstname . ' ' .auth()->user()->lastname }}</th>
                </tr>
                <tr>
                    <td colspan="5" align="left">Generated On: {{ date('F j,Y g:i:s A') }}</td>
                </tr>
            </table>
        @endif
    </body>
</html>